<?php

$modulo = 'geral';

echo $this->headLink()                   
                 ->prependStylesheet($this->basePath( $modulo ) . '/bootstrap/css/jquery-ui.min.css');


$this->layout()->setVariable('titulo', ' Cadastro Post <i class="fa fa-sticky-note"></i>');

echo $this->form()->openTag($form);

$form->prepare();
$form->setValidationGroup('titulo', 'conteudo', 'status');

?>

<div class="form-group col-md-12">
	<fieldset>
    	<legend>Dados</legend>
			<div class="row">		
				<div class="form-group col-md-4">	
					<?= $this->formLabel($form->get('titulo')); ?>
					<?= $this->formInput($form->get('titulo')); ?>
				</div>			  	   	   		 			   
		   </div>
		   <div class="row">		
		   		<div class="form-group col-md-2 tiny">	
					<?= $this->formLabel($form->get('conteudo')); ?>
					<?=  $this->formTextArea($form->get('conteudo')); ?>
			    </div>
		  </div>	
		  <div class="row">
			  <div class="form-group col-md-2">
		   				<?= $this->formLabel($form->get('cdstatus')); ?>
						<?=  $this->formSelect($form->get('cdstatus')); ?>
			  </div>
		  </div>
 
	</fieldset>
	
	
	     
	<br/>
	<div class="row text-center">
		<div class="group-btn">	
			<?= $this->formInput($form->get('salvar')); ?>
			<?= $this->formInput($form->get('voltar')); ?>
		</div>
	</div>
	
</div>	


<?php


echo $this->form()->closeTag($form);

echo '<div style="display:none;" id="dialog-cpfinvalido" title="">
	  CPF inválido!
      </div>';

echo $this->headScript()
			->prependFile($this->basePath( $modulo ) . '/plugins/tiny_mce/tiny_mce.js')
            ->prependFile($this->basePath( $modulo ) . '/dist/js/demo.js')
            ->prependFile($this->basePath( $modulo ) . '/dist/js/app.min.js')
            ->prependFile($this->basePath( $modulo ) . '/plugins/fastclick/fastclick.js')
     		->prependFile($this->basePath( $modulo ) . '/plugins/slimScroll/jquery.slimscroll.min.js')
            ->prependFile($this->basePath( $modulo ) . '/bootstrap/js/bootstrap.min.js')
            ->prependFile($this->basePath( 'empresa' ) . '/js/funcoes-post.js')
            ->prependFile($this->basePath( $modulo ) . '/plugins/jQueryUI/jquery-ui.min.js')
            ->prependFile($this->basePath( $modulo ) . '/plugins/jQuery/jQuery-2.1.4.min.js')
            
          
             
        ; 	
?>




