

<?php $modulo = 'geral';


	use Zend\Session\Container;
	$sessao = new Container('mensagemlogin');
	

	
	//Se vier do cadastro
		if($sessao->mensagem != null){
			echo 
			"<div id='mensagem-alert' class='alert btn-success text-center' role='alert'>
				$sessao->mensagem
			</div>";
		}

?>
	<!--Se vier da exclusão via ajax -->
	<div id='mensagem-alert'></div>


<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>BlogTeste | Entrar</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">


  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

  
    <!-- Bootstrap 3.3.5 -->
    <!-- Theme style -->
    <!-- iCheck -->
     <?php echo $this->headLink()
   						->prependStylesheet($this->basePath( $modulo ) . '/bootstrap/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath( $modulo ) . '/dist/css/AdminLTE.min.css')
                        ->prependStylesheet($this->basePath( $modulo ) . '/plugins/iCheck/square/blue.css')          
                         ?>


  <!--[if lt IE 9]> -->
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="<?= '/' ?>"><b>Blog</b>Teste</a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Informe seus dados para realizar o cadastro.</p>

    <form action="<?= '/empresa/login/cadastrar' ?>" method="post">
    
     <div class="input-group">
     	<span class="input-group-addon">
     		<i class="fa fa-user"></i>
     	</span>
     	<input class="form-control" type="text" name="nmusuario"  placeholder="Nome Completo" required='required'>
     </div>
     <br/>
     <div class="input-group">
     	<span class="input-group-addon">
     		<i class="fa fa-envelope"></i>
     	</span>
     	<input class="form-control" type="email" name="usuario"  placeholder="Email" required='required'>
     </div>
     <br/>
     <div class="input-group">
      	<span class="input-group-addon">
      		<i class="fa fa-lock" ></i>
      	</span>
        <input type="password" class="form-control" name="senha" placeholder="Senha" required='required'>      
      </div>
      <br/>
      <div class="row">
        <div class="col-xs-12">
          <button type="submit" class="btn btn-primary btn-block btn-flat">Cadastrar</button>
        </div>
        <!-- /.col -->
      </div>
      <br/>
      <a href="/" class="text-center">Voltar</a> 
    </form>

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

</body>
</html>

<?php
	$sessao->getManager()->getStorage()->clear('mensagemlogin');
?>
